### ISSUE TITLE
LynxExplorer-noasan-release.apk crashes upon launch in my 9.1 android device

### ISSUE THREAD

**Issue by mmarvelous078** [lynx-family/lynx#127]
The LynxExplorer for android fails to launch in my Android 9.1 device.

**Comment by mitchilling** [comment]
Hi, any chance you could provide the logcat here? Plus, the released apk contains arm64 libraries only. Please make sure your phone is of the same arch.

**Comment by Kingatnuaa0528** [comment]
Hi, we have fixed this issue. The explorer APK available for download on the official website currently supports three architectures: arm64, arm32, and x86. You can download it again and start using it.

**Comment by mmarvelous078** [comment]
Which official website? Because the one released on Github is still the same.

**Comment by Kingatnuaa0528** [comment]
You can download the following [link](https://github.com/lynx-family/lynx/releases/latest/download/LynxExplorer-noasan-release.apk) and re-verify it locally. If there are still any issues, please kindly provide the logcat of the app's startup process.

**Comment by mmarvelous078** [comment]
> Hi, any chance you could provide the logcat here? Plus, the released apk contains arm64 libraries only. Please make sure your phone is of the same arch.

Here is the Logcat:
03-07 12:18:54.020  9482  9482 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getCutout()Landroid/view/DisplayCutout; in class Landroid/view/Display; or its super classes (declaration of 'android.view.Display' appears in /system/framework/framework.jar!classes2.dex)

**Comment by mmarvelous078** [comment]
> You can download the following [link](https://github.com/lynx-family/lynx/releases/latest/download/LynxExplorer-noasan-release.apk) and re-verify it locally. If there are still any issues, please kindly provide the logcat of the app's startup process.

Thanks. Let me install it, I will get back to you shortly.

**Comment by mmarvelous078** [comment]
> You can download the following [link](https://github.com/lynx-family/lynx/releases/latest/download/LynxExplorer-noasan-release.apk) and re-verify it locally. If there are still any issues, please kindly provide the logcat of the app's startup process.

**Lynx Explorer Crash Log - 07 March 2025**

Lynx Explorer is crashing due to a **NoSuchMethodError** when calling `getCutout()` on `android.view.Display`. Additional issues include unregistered services and a potential memory leak monitor missing.

1. Debugger Issue
```
03-07 12:37:03.709 23365 23365 E m.lynx.explore: Not starting debugger since process cannot load the jdwp agent.
```

2. Fatal Exception - NoSuchMethodError
```
03-07 12:37:04.365 23365 23365 E AndroidRuntime: FATAL EXCEPTION: main
03-07 12:37:04.365 23365 23365 E AndroidRuntime: Process: com.lynx.explorer, PID: 23365
03-07 12:37:04.365 23365 23365 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getCutout()Landroid/view/DisplayCutout;
```

3. Memory Leak Monitor Missing
```
03-07 12:37:04.270 23365 23380 E MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
Likely not critical, but could indicate a missing debug tool.
```

4. VSync Issue: 
```
03-07 12:37:04.273 23365 23365 E VSyncMonitor: getRefreshRate failed: Attempt to invoke virtual method 'java.lang.Object java.lang.ref.WeakReference.get()' on a null object reference.
Possible null reference issue in VSyncMonitor.
```

5. Service Unregistration Issues:
```
03-07 12:37:04.212 23365 23365 E DebugRouterServiceCenter: IDebugRouterReportService is unregistered
03-07 12:37:04.215 23365 23365 E DebugRouterServiceCenter: IUSBHijackService is unregistered
Indicates some services were unregistered unexpectedly.
```

**Comment by coolkiid** [comment]
@mmarvelous078 Thanks for your feedback! I'm the developer of Android Lynx Explorer. 

The major reason for the crash is:

```plaintext
03-07 12:37:04.365 23365 23365 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getCutout()Landroid/view/DisplayCutout;
```

The code relevant to this is as follows:
https://github.com/lynx-family/lynx/blob/a8798502f92ee79b80d93fe91f591091d97e3020/explorer/android/lynx_explorer/src/main/java/com/lynx/explorer/LynxViewShellActivity.java#L162-L175

Yes, it is a bug.  The `DisplayCutout cutout = display.getCutout();` was added in [api 29](https://developer.android.com/reference/android/view/Display#getCutout()). I think adding an if statement before it can solve this easily, would you like to give it a go? Or I will submit a patch later to fix this.

**Comment by jameszokah** [comment]
@coolkiid, please check whether this would workout

```java

public boolean isNotchScreen() {
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.P) {
        return false;
    }
    
    WindowManager windowManager = getSystemService(WindowManager.class);
    if (windowManager == null) {
        return false;
    }
    
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
        // Android 10+ approach
        Display display = windowManager.getDefaultDisplay();
        DisplayCutout cutout = display.getCutout();
        return cutout != null;
    } else {
        // Android 9 approach
        WindowInsets windowInsets = windowManager.getCurrentWindowMetrics().getWindowInsets();
        DisplayCutout cutout = windowInsets.getDisplayCutout();
        return cutout != null;
    }
}

```

**Comment by coolkiid** [comment]
@jameszokah Looks great! Would you like to submit a pr?

**Comment by jameszokah** [comment]
@coolkiid I've submitted a pr

**Comment by coolkiid** [comment]
This issue should be fixed [in this commit](https://github.com/lynx-family/lynx/blob/b1f02ebe1883d0573c605c1c2d7a0823ea190e81/explorer/android/lynx_explorer/src/main/java/com/lynx/explorer/LynxViewShellActivity.java).
