### ISSUE TITLE
[Bug]: Application is crashing when using Kotlin nullable String

### ISSUE THREAD

**Issue by darekbx** [lynx-family/lynx#2548]
### System Info

Lynx 3.3.0

### Details

Application is crashing, when using custom native module written in Kotlin, where LynxMethod returns `String?`.  

Crash log:
```
java_vm_ext.cc:591] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received NULL jstring
java_vm_ext.cc:591]     in call to GetStringUTFChars
java_vm_ext.cc:591]     from void android.os.MessageQueue.nativePollOnce(long, int)
```

### Reproduce Steps

Add and register this native module to Android app:
```kotlin
// Kotlin
class NativeTestModule(private val context: Context) : LynxModule(context) {
    @LynxMethod
    fun getItem(): String? {
        return null
    }
}

//...

LynxEnv.inst().registerModule("NativeTestModule", NativeTestModule::class.java)
```

Add typing to web app:
```tsx
  NativeTestModule: {
    getItem(): string | null;
  }
```

Call method:
```tsx
NativeModules.NativeTestModule.getItem();
```

**Comment by OverWatch-Winder** [comment]
@darekbx Thanks.this issue has been fixed in version 3.3.1.😊
https://github.com/lynx-family/lynx/commit/6b81de540a834dc0647d1f4a218e914fd0dcb1f6

**Comment by darekbx** [comment]
@mitchilling @OverWatch-Winder  Can you repopen this issue? This is not fixed correctly. Yes, the app is not crashing, but for nullable value is returned empty string, not null on JS side.
 
This typing will not work: 
```typescript
getItem(key: string): string | null;
```

Additionaly there's difference between Android and iOS. Where on iOS nullable Swift value returns null on JS side.
